var fs = require('fs');
var path = require('path');

// Replace with your unique name
exports.appName = 'TaxiGoDriver';

// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
exports.gcmServerApiKey = 'Your-server-api-key';

// You may want to use your own credentials here
var apns={
};
apns.cert = path.resolve(__dirname, 'credentials', 'PushDriverCert.pem');
apns.key = path.resolve(__dirname, 'credentials', 'PushDriverKey.pem');//'PushDriverKey.pem';

exports.apnsCertData = fs.readFileSync(apns.cert);
exports.apnsKeyData = fs.readFileSync(apns.key);
exports.apns = apns;

//--- Helper functions ---

function readCredentialsFile(name) {
  return fs.readFileSync(
    path.resolve(__dirname, 'credentials', name),
    'UTF-8'
  );
}